FROM ubuntu:26.04

ENV DEBIAN_FRONTEND=noninteractive 
ENV TZ=Europe/Madrid
ENV VER_NAME=2.5.0

# tzdata: Configure region
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install dependencies
RUN apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
        aptitude apt-utils \
        zlib1g-dev ca-certificates pkg-config \
        software-properties-common gpg-agent \
        curl libcurl3-dev \
        wget rsync \
        sudo less \
        \
        git libtool \
        jq \
        \
        zip unzip \
        \
        ubuntu-restricted-extras \
        && \
    apt-get clean

RUN apt update && apt-get install -y \
        nodejs \
        npm

# WepSIM
WORKDIR /
RUN wget -N https://github.com/wepsim/wepsim/releases/download/v${VER_NAME}/wepsim-${VER_NAME}.zip
RUN unzip  wepsim-${VER_NAME}.zip
RUN mv     wepsim-${VER_NAME}        /wepsim
RUN cd /wepsim && \
    cp wepsim-classic.html wepsim.html && \
    npm install terser jq jshint yargs clear inquirer@8.2.6 fuzzy inquirer-command-prompt inquirer-autocomplete-prompt@1

# Initial workspace
RUN mkdir /workspace
WORKDIR   /workspace

ENTRYPOINT ["/wepsim/wepsim.sh"]
