#!/bin/bash
set -x

jshint ./sim_core/sim_core_ui_help.js
jshint ./sim_core/sim_cfg.js
jshint ./sim_core/sim_core.js
jshint ./sim_core/sim_core_ui_console.js
jshint ./sim_core/sim_stateshots.js
jshint ./sim_hw/sim_hw_poc/sim_hw_board.js
jshint ./sim_hw/sim_hw_poc/sim_hw_kbd.js
jshint ./sim_hw/sim_hw_poc/sim_hw_scr.js
jshint ./sim_hw/sim_hw_poc/sim_poc.js
jshint ./sim_hw/sim_hw_poc/sim_hw_mem.js
jshint ./sim_hw/sim_hw_index.js
jshint ./sim_hw/sim_hw_ep/sim_hw_io.js
jshint ./sim_hw/sim_hw_ep/sim_hw_board.js
jshint ./sim_hw/sim_hw_ep/sim_hw_kbd.js
jshint ./sim_hw/sim_hw_ep/sim_hw_scr.js
jshint ./sim_hw/sim_hw_ep/sim_hw_mem.js
jshint ./sim_hw/sim_hw_ep/sim_ep.js
jshint ./sim_hw/sim_hw_values.js
jshint ./sim_sw/sim_lang.js
jshint ./wepsim/wepsim_url.js
jshint ./wepsim/wepsim_native.js
jshint ./wepsim/wepsim_tutorial.js
jshint ./wepsim/wepsim_voice.js
jshint ./wepsim/wepsim_node.js
jshint ./wepsim/wepsim_config.js
jshint ./wepsim/wepsim_help.js
jshint ./wepsim/breakpointicons.js
jshint ./wepsim/tutorials.js
jshint ./wepsim/wepsim_example.js
jshint ./wepsim/wepsim_misc.js
jshint ./wepsim/es/welcome-es.js
jshint ./wepsim/es/tour-es.js
jshint ./wepsim/es/simpleusage-es.js
jshint ./wepsim/es/config-es.js
jshint ./wepsim/es/examples-es.js
jshint ./wepsim/es/help-es.js
jshint ./wepsim/en/tour-en.js
jshint ./wepsim/en/simpleusage-en.js
jshint ./wepsim/en/welcome-en.js
jshint ./wepsim/en/help-en.js
jshint ./wepsim/en/examples-en.js
jshint ./wepsim/en/config-en.js
